"""
EEG Signal Visualizer + Motor Imagery Classifier
--------------------------------------------------
Streamlit app for exploring EEG motor-imagery data (PhysioNet EEGMMIDB)
and running a trained CSP+LDA classifier that predicts whether a subject
was imagining moving their LEFT fist or RIGHT fist.

This app loads PRECOMPUTED data/model files only -- it does not
download or train anything at runtime, so it stays fast and light
on Streamlit Community Cloud.

Run locally with: streamlit run app.py
"""

import os
import numpy as np
import pandas as pd
import joblib
import streamlit as st
import plotly.graph_objects as go

from utils import FREQ_BANDS, CLASS_LABELS, epoch_bandpowers

DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
MODEL_PATH = os.path.join(DATA_DIR, "csp_lda_model.joblib")
DEMO_DATA_PATH = os.path.join(DATA_DIR, "demo_data.npz")

st.set_page_config(page_title="EEG BCI Visualizer", page_icon="🧠", layout="wide")


@st.cache_resource
def load_model():
    return joblib.load(MODEL_PATH)


@st.cache_data
def load_demo_data():
    npz = np.load(DEMO_DATA_PATH, allow_pickle=True)
    return {
        "X": npz["X"],
        "y": npz["y"],
        "subject_ids": npz["subject_ids"],
        "ch_names": [str(c) for c in npz["ch_names"]],
        "sfreq": float(npz["sfreq"]),
        "tmin": float(npz["tmin"]),
        "tmax": float(npz["tmax"]),
        "synthetic": bool(npz["synthetic"]) if "synthetic" in npz else False,
    }


def missing_data_message():
    st.error(
        "No precomputed model/data found in `data/`.\n\n"
        "This app requires `data/csp_lda_model.joblib` and `data/demo_data.npz`, "
        "generated by running `train_model.py` locally (it downloads PhysioNet "
        "EEG data and trains the classifier). Run that script once, then commit "
        "the `data/` folder to your repo before deploying."
    )


def main():
    st.title("🧠 EEG Signal Visualizer & Motor Imagery Classifier")
    st.caption(
        "Explore real EEG recordings from the PhysioNet EEG Motor Movement/Imagery "
        "Dataset and see a trained CSP+LDA model classify imagined left vs. right "
        "fist movement."
    )

    if not (os.path.exists(MODEL_PATH) and os.path.exists(DEMO_DATA_PATH)):
        missing_data_message()
        st.stop()

    model = load_model()
    data = load_demo_data()

    if data.get("synthetic"):
        st.warning(
            "⚠️ **Running on synthetic placeholder data.** These signals are "
            "computer-generated (not real EEG recordings) and exist so the app "
            "can be tested end-to-end. Run `train_model.py` locally to replace "
            "`data/` with a model trained on real PhysioNet EEG recordings "
            "before sharing results publicly."
        )

    X, y = data["X"], data["y"]
    ch_names = data["ch_names"]
    sfreq = data["sfreq"]
    tmin, tmax = data["tmin"], data["tmax"]
    n_epochs, n_channels, n_times = X.shape
    time_axis = np.linspace(tmin, tmax, n_times)

    # ---- Sidebar controls ----
    st.sidebar.header("Controls")
    subject_options = sorted(set(data["subject_ids"].tolist()))
    selected_subject = st.sidebar.selectbox("Subject", subject_options, format_func=lambda s: f"Subject {s:03d}")

    subject_epoch_idxs = np.where(data["subject_ids"] == selected_subject)[0]
    trial_choice = st.sidebar.selectbox(
        "Trial",
        list(range(len(subject_epoch_idxs))),
        format_func=lambda i: f"Trial {i + 1} (true label: {CLASS_LABELS[int(y[subject_epoch_idxs[i]])]})",
    )
    epoch_idx = subject_epoch_idxs[trial_choice]

    default_channels = [c for c in ["C3", "Cz", "C4"] if c in ch_names] or ch_names[:3]
    selected_channels = st.sidebar.multiselect(
        "Channels to plot", ch_names, default=default_channels
    )

    st.sidebar.markdown("---")
    st.sidebar.caption(
        f"Demo set: {n_epochs} epochs · {n_channels} channels · "
        f"{sfreq:.0f} Hz · {tmax - tmin:.0f}s windows"
    )

    epoch = X[epoch_idx]  # (n_channels, n_times)
    true_label = CLASS_LABELS[int(y[epoch_idx])]

    # ---- Layout ----
    col_left, col_right = st.columns([2, 1])

    with col_left:
        st.subheader("Raw EEG Waveform")
        if selected_channels:
            fig = go.Figure()
            for ch in selected_channels:
                ch_idx = ch_names.index(ch)
                fig.add_trace(go.Scatter(x=time_axis, y=epoch[ch_idx], mode="lines", name=ch))
            fig.update_layout(
                xaxis_title="Time (s)", yaxis_title="Amplitude (µV)",
                height=420, margin=dict(l=10, r=10, t=30, b=10),
                legend=dict(orientation="h", yanchor="bottom", y=1.02),
            )
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.info("Select at least one channel in the sidebar to plot the waveform.")

        st.subheader("Band Power (averaged across all channels)")
        band_powers = epoch_bandpowers(epoch, sfreq)
        bp_df = pd.DataFrame({"Band": list(band_powers.keys()), "Power": list(band_powers.values())})
        fig_bp = go.Figure(go.Bar(x=bp_df["Band"], y=bp_df["Power"]))
        fig_bp.update_layout(height=320, margin=dict(l=10, r=10, t=20, b=10), yaxis_title="Power")
        st.plotly_chart(fig_bp, use_container_width=True)

    with col_right:
        st.subheader("Classifier Prediction")
        pred_proba = model.predict_proba(epoch[np.newaxis, ...])[0]
        pred_class = int(np.argmax(pred_proba))
        pred_label = CLASS_LABELS[pred_class]
        confidence = float(pred_proba[pred_class])

        st.metric("Predicted", pred_label, f"{confidence * 100:.1f}% confidence")
        st.caption(f"Ground truth: **{true_label}**")
        if pred_label == true_label:
            st.success("✅ Correct prediction")
        else:
            st.warning("⚠️ Misclassified")

        st.markdown("**Class probabilities**")
        proba_df = pd.DataFrame({
            "Class": [CLASS_LABELS[0], CLASS_LABELS[1]],
            "Probability": pred_proba,
        })
        fig_proba = go.Figure(go.Bar(x=proba_df["Probability"], y=proba_df["Class"], orientation="h"))
        fig_proba.update_layout(height=200, margin=dict(l=10, r=10, t=10, b=10), xaxis_range=[0, 1])
        st.plotly_chart(fig_proba, use_container_width=True)

        st.markdown("---")
        st.markdown(
            "**How this works:** the model uses Common Spatial Patterns (CSP) "
            "to find channel combinations that best separate left- vs right-fist "
            "imagery, then a Linear Discriminant Analysis (LDA) classifier makes "
            "the final call. This is the classic, well-validated approach in BCI "
            "motor imagery literature."
        )

    st.markdown("---")
    with st.expander("About this dataset"):
        st.write(
            "Data is drawn from the PhysioNet EEG Motor Movement/Imagery Dataset: "
            "64-channel EEG recordings of subjects performing or imagining left "
            "fist, right fist, both fists, and both feet movements. This demo "
            "uses only the imagined left-fist vs. right-fist trials."
        )


if __name__ == "__main__":
    main()
